"use strict";

const generateBtn = document.getElementById("generate");
const copyBtn = document.getElementById("copy");
const output = document.getElementById("output");
const statusEl = document.getElementById("status");

function setStatus(message, isError) {
  statusEl.textContent = message;
  statusEl.className = isError ? "error" : "ok";
}

// Build a Netscape cookies.txt body that yt-dlp can read. This is the exact
// format the bot decodes from YT_COOKIES_B64 (base64 -> cookies.txt).
function toNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by YouTube Cookie Exporter",
    "",
  ];
  for (const c of cookies) {
    const includeSubdomains = !c.hostOnly;
    let domain = c.domain || "";
    if (includeSubdomains && !domain.startsWith(".")) {
      domain = "." + domain;
    }
    // yt-dlp recognises the #HttpOnly_ prefix for HttpOnly cookies.
    if (c.httpOnly) {
      domain = "#HttpOnly_" + domain;
    }
    const flag = includeSubdomains ? "TRUE" : "FALSE";
    const path = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = c.session || !c.expirationDate ? 0 : Math.floor(c.expirationDate);
    lines.push([domain, flag, path, secure, String(expiry), c.name, c.value].join("\t"));
  }
  return lines.join("\n") + "\n";
}

// UTF-8 safe base64 encoding (matches Go's base64.StdEncoding on the bot side).
function toBase64(text) {
  const bytes = new TextEncoder().encode(text);
  let binary = "";
  for (const b of bytes) {
    binary += String.fromCharCode(b);
  }
  return btoa(binary);
}

async function generate() {
  setStatus("Reading cookies…", false);
  output.value = "";
  try {
    const cookies = await chrome.cookies.getAll({ domain: "youtube.com" });
    if (!cookies || cookies.length === 0) {
      setStatus(
        "No youtube.com cookies found. Sign in to YouTube in this browser, then try again.",
        true
      );
      return;
    }
    output.value = toBase64(toNetscape(cookies));
    setStatus(
      "Exported " +
        cookies.length +
        " cookies. Copy the value below into .env as YT_COOKIES_B64.",
      false
    );
  } catch (err) {
    setStatus("Error: " + (err && err.message ? err.message : String(err)), true);
  }
}

async function copyOutput() {
  if (!output.value) {
    setStatus("Nothing to copy yet — click Generate first.", true);
    return;
  }
  try {
    await navigator.clipboard.writeText(output.value);
  } catch (err) {
    output.select();
    document.execCommand("copy");
  }
  setStatus("Copied to clipboard.", false);
}

generateBtn.addEventListener("click", generate);
copyBtn.addEventListener("click", copyOutput);
